int putchar (int character);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _putchar (int character);
int islower(int c);
int _isalpha(int c);
int isalpha(int c);
int print_sign(int n);
int _abs(int);
int abs(int);
int print_last_digit(int);
int add(int, int);
void print_to_98(int n);
